Add replicaCount configuration to minecraft-proxy chart
itzg/minecraft-server-charts pull request #221
Opened 2024-08-14 06:07 UTC by by77er

2024-08-14 12:09 UTC, billimek requested changes

2024-08-14 12:09 UTC, billimek commented on charts/minecraft-proxy/Chart.yaml
> +version: 4.0.0
This looks good but I don't know if the nature of the change requires a major version bump.
 
```suggestion
version: 3.8.0
```

2024-08-15 01:32 UTC, itzg approved these changes

2024-08-15 12:24 UTC, itzg commented
@billimek github is blocking me from merging until you re-review. (I'm sure I could fix via admin settings, but that's too much work 😀)

2024-08-15 13:02 UTC, billimek approved these changes

2024-08-15 13:02 UTC, merged